# Generated by Django 4.0.1 on 2022-01-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendedores',
            new_name='Vendedor',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
