# Generated by Django 4.0.1 on 2022-02-20 17:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
