# Generated by Django 4.0.1 on 2022-02-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0003_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='Borrador', max_length=10),
        ),
    ]
