# Generated by Django 4.0.1 on 2022-01-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0003_rename_clientes_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
