# Generated by Django 4.0.1 on 2022-01-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0004_rename_productos_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='prenda',
        ),
    ]
