# Generated by Django 4.0.1 on 2022-02-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0006_alter_cliente_email_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='vendedores'),
        ),
    ]
