# Generated by Django 4.0.1 on 2022-02-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0007_vendedor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vendedores'),
        ),
    ]
