# Generated by Django 4.0.1 on 2022-02-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderShop', '0011_alter_vendedor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
